<!-- <style>
    .footer {
        background-color: black;
        height: 600px;
        padding-left: 120px;
        padding-right: 120px;
    }

    /* footer1 */
    .footer-1 {
        color: white;
        height:250px;
    }

    .footer-1_title {
        width: 22%;
        float: left;
    }

    .footer-1_title>p {
        font-weight: 500;
        font-size: 45px;
        color: #D7B797;
        line-height: 50px;
        padding-top:35px;
    }

    .footer-1_form {
        width: 65%;
        float: right;
        padding-top: 40px;
    }

    .form {
        padding-left: 130px;
    }

    .footer-1_form>p {
        font-size: 18px;
    }

    .footer-1_form>div>form>div>input {

        border-radius: 20px;
        color: white;
        font-size: 11px;
        border: 1px solid white;
        background-color: black;
        line-height: 3;
        scale: 1.5;
    }

    .form-text {
        margin-left: -10px;
        padding-bottom: 15px;
        font-size: 16px;
    }

    .footer-1_form>div>form>div {
        padding-bottom: 35px;
    }

    .form_submit {
        display: flex;
        width: 101%;
        margin-left: -5px;
    }

    .form_ip1 {
        width: 80%;
    }

    .form_submit>div>input {
        width: 77%;
        border-radius: 20px;
        color: white;
        font-size: 11px;
        border: 1px solid white;
        background-color: black;
        line-height: 2.6;
        scale: 1.5;
    }

    .ip2 {
        margin-left: -30px;
    }

    .ip3 {
        margin-left: 0 !important;
    }

    .form_submit-left {
        width: 80%;
        margin-left: -5px;
    }

    .form_submit-right {
        width: 25%;
    }

    .form_submit-right>input {
        margin-left: 10px;

    }

    /* footer 2 */

    .footer-2 {
        color: white;
    }

    .img_dafc {
        width: 15%;
    }

    .footer2_content {
        display: flex;
        justify-content: space-between;
    }
</style>



<div class="footer">
    <div class="footer-1">
        <div class="footer-1_title">
            <p>LATEST FROM DAFC</p>
        </div>
        <div class="footer-1_form">
            <div class="form-text">
                <p>Be the first to know about exciting new collection, special events, store openings and much more.</p>
            </div>
            <div class="form">
                <form class="form_address">
                    <div class="form_ip1">
                        <input class="ip1" type="email" placeholder="Enter your email address">
                    </div>
                    <div class="form_submit">
                        <div class="form_submit-left">
                            <input class="ip2" type="text" placeholder="Enter your phone number">
                        </div>
                        <div class="form_submit-right">
                            <input class="ip3" type="submit" value="SUBMIT">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="footer-2">
        <div class="img_dafc">
            <img src="<?php echo $this->getViewFileUrl('images/LogoDAFC_White.png') ?>" alt="">
        </div>
        <div class="footer2_content">
            <div class="footer-2_title">
                <span>
                    <p style="font-weight:bold">DAFC - A subsidiary of IPPG</p>
                    <p>Centec Tower, 72-74 Nguyen Thi Minh Khai, District 3, HCMC, Vietnam</p>
                    <p>Hotline: 19002666</p>
                    <p>support@cs.dafc.com.vn</p>
                </span>
                <img style="scale:0.3; margin-left:-110px; margin-top:-40px" src="<?php echo $this->getViewFileUrl('images/image_2.png') ?>" alt="">
            </div>
            <div class="footer-2_contact">
                <span>
                    <p style="font-weight:bold">Contact</p>
                    <p><a href="#" style="color:white">About DAFC</a></p>
                    <p><a href="#" style="color:white">Careers</a></p>
                    <p><a href="#" style="color:white">Contact</a></p>
                </span>
            </div>
            <div class="footer-2_customer">
                <span>
                    <p style="font-weight:bold">Customer Care</p>
                    <p><a href="#" style="color:white">Membership program</a></p>
                    <p><a href="#" style="color:white">FAQ</a></p>
                    <p><a href="#" style="color:white">Shipping</a></p>
                    <p><a href="#" style="color:white">Return & Exchange</a></p>
                </span>
            </div>
            <div class="footer-2_legal">
                <span>
                    <p style="font-weight:bold">Legal</p>
                    <p><a href="#" style="color:white">Privacy policy</a></p>
                    <p><a href="#" style="color:white">Terms & Conditions</a></p>
                    <p><a href="#" style="color:white">Cookie Policy</a></p>
                    <p><a href="#" style="color:white">Product inqueries</a></p>
                    <p><a href="#" style="color:white">Payment</a></p>
                </span>
            </div>
            <div class="footer-2_follow">
                <span>
                    <p style="font-weight:bold">Follow us</p>
                    <p><a href="#" style="color:white">Facebook</a></p>
                    <p><a href="#" style="color:white">Instagram</a></p>
                    <p><a href="#" style="color:white">Linkedln</a></p>
                    <p><a href="#" style="color:white">Zalo</a></p>
                </span>
            </div>
        </div>
    </div>
</div> -->