<style>
    .container {
        margin-top: -30px;
    }

    .container_title {
        position:absolute;
        margin-top: -440px; 
        margin-left: 230px;
    }

    .container_title-2 {
        position:absolute;
        margin-top: -440px; 
        margin-left: 1380px;
    }
    .title {
        color:white !important;
        font-size:28px;
        text-decoration:none !important;
    }
    .title_sublink{
        color:white !important; 
        text-decoration:underline;
        font-size:15px;
    }

</style>

<div class="container">
    <img src="<?php echo $this->getViewFileUrl('images/Image 2 ratio 1_1.png') ?>" alt="">
    <div class="container_title">
        <p ><a href="http://localhost:8099/bai1/hello/world" class="title">WOMEN</a></p>
        <p><a href="http://localhost:8099/bai1/hello/world" class="title_sublink">Shop women</a></p>
    </div>
    <div class="container_title-2">
        <p ><a href="http://localhost:8099/bai1/hello/world" class="title">MEN</a></p>
        <p><a href="http://localhost:8099/bai1/hello/world" class="title_sublink">Shop  men</a></p>
    </div>
</div>